### ISSUE TITLE
Add preprocessing hook function for result of request

### ISSUE THREAD

**Issue by chuoke** [rapidjs/rapid.js#14]

**Comment by drewjbartlett** [comment]
I actually had this feature and then removed it on initial release. This can actually be achieved in the [apiConfig](http://rapidjs.io/docs#configuration-apiConfig). Check out `transformRequest` on axios as well: https://github.com/mzabriskie/axios#request-config. 

I think I could write a wrapper around `transformRequest` in the config called `parse () {}` or something

**Comment by chuoke** [comment]
Understand. but what if just use rapid without `axios` ? How to do what such as preprocessing ?
That is awesome you do, I have same annoyance, but no time and not professional, so I wish you can do it better !

**Comment by drewjbartlett** [comment]
As of now there's no way to use rapid without `axios`. It's dependent on `axios` as its promise-based http client. So all requests are actually made through it. Either way, I can definitely add my own version of this soon!
