### ISSUE TITLE
[Question]: How do imports work?

### ISSUE THREAD

**Issue by BrainMaestro** [rapidjs/rapid.js#23]
I see that there's no top level `index.js` or even on in the `src` folder that reexports `Rapid` and `Auth`. The docs suggest `import Rapid from 'rapid.js';` which seems like it clearly won't work.
Am I missing something here?

**Comment by drewjbartlett** [comment]
https://github.com/rapidjs/rapid.js/blob/master/package.json#L5

That tells npm where the main entry point is :)

**Comment by BrainMaestro** [comment]
Oh right. Just a little unusual then
