### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by BrainMaestro** [rapidjs/rapid.js#24]
For people that prefer to work in typescript, would you be interested in adding type definitions? I can work on the PR if you are.

**Comment by drewjbartlett** [comment]
@BrainMaestro I actually am not crazy familiar with TS. I would LOVE to learn it more. I host a meetup in my town and we are going over TS in the next talk https://www.meetup.com/BendJS/events/245313573/. Hoping to learn some then!

My only concern with making a PR at this point in time is that I want to make sure I can still easily update and maintain the code which I'm not sure I'll be able without knowing TS very much.

**Comment by BrainMaestro** [comment]
Oh, I'm not suggesting that you convert the existing code to typescript. I'm suggesting adding a single definition file that contains the type information for the entire project. Similar to [this](https://github.com/axios/axios/blob/master/index.d.ts)

**Comment by drewjbartlett** [comment]
Ah okay. I misunderstood. Well then, yeah, if it's not going to effect anyone who doesn't use TS, I am all in! Feel free to submit a PR

**Comment by RichiCoder1** [comment]
I had the exact same thought when I first saw this library :). The big question will be how best to flow types 🤔
