### ISSUE TITLE
POST polluted with params from previous GET

### ISSUE THREAD

**Issue by miljan-aleksic** [rapidjs/rapid.js#30]
Hi, I am using rapid.js v1.0.11 and seems there is a bug.

```js
const query = {...}
Api.withParams(query).all()
  // sending Query string parameters - OK

const data = {...}
Api.withParams(data).post()
  // sending Request Payload - OK
  // sending Query string parameters from previous request - NOT OK
```

Or perhaps I am missing something...

**Comment by drewjbartlett** [comment]
@miljan-aleksic can you post a few example urls and also an example of the data passed so I can have a look?

**Comment by miljan-aleksic** [comment]
Do you have an example jsfiddle or codpen to start from?

**Comment by drewjbartlett** [comment]
@miljan-aleksic I don't have anything set up. I just wanted to see your issue if possible :)

**Comment by miljan-aleksic** [comment]
I can't reproduce it in a clean environment. Most likely it was an integration issue. Closing this issue and thanks anyway :)
