### ISSUE TITLE
Version 2

### ISSUE THREAD

**Issue by drewjbartlett** [rapidjs/rapid.js#40]
Making a place to document the changes on V2

 - [ ] Rewrite entirely in TypeScript
 - [ ] Properly declare and import type definitions #41 
-  [ ] Fix all tests #46 
 - [x] `api` renamed to `http`
 - [x] swap `qs` for `qs-stringify` since we only use that method https://www.npmjs.com/package/qs-stringify
- [x] Allow for other promise-based http services to be used in place of axios with injection
 - [ ] Rewrite version 2 docs to reflect updates
 - [ ] Rewrite version 2 docs in nuxt (and maybe markdown)
 - [ ] Extract debugger to allow easier testing and optionally include based off `ENV`
 - [ ] Extract custom routes into package
- [ ] Add plugin system to allow syntax like `rapid.use(customRouter)`
- [x] Fix nasty inheritance chain

**Comment by drewjbartlett** [comment]
@mgred I'm going to add a lot more features here but I figured for now we can use this to track progress and such. Feel no obligation to help me out, but if you want to it'd be much appreciated :D

**Comment by mgred** [comment]
@drewjbartlett that sounds like a plan! I will get into your branch over the weekend and see if there is something to add here.

**Comment by drewjbartlett** [comment]
@mgred Awesome thanks! More than anything I need help getting proper ts declarations and compiling in place. Right now I am a bit lost on some of those things :D

**Comment by mgred** [comment]
@drewjbartlett Alright, no problem! I think I can help there.

**Comment by yihou** [comment]
Hi @drewjbartlett, I think I can help out, where can I start from? 
What is the build tool that you guys are using?

**Comment by ctsstc** [comment]
I noticed the branch for v2 is 10 commits behind master, hopefully nothing too breaking to try and get caught up with. As mentioned in my PR into the v2 branch I would recommend looking at removing manually written d.ts files and let those be generated in the TS compile via some settings in the ts config.

**Comment by mgred** [comment]
> I would recommend looking at removing manually written d.ts files and let those be generated in the TS compile via some settings in the ts config
I think this is the way to go. Basically `{declaration: true}` in the `tsconfig.json` should do the trick.

> I think if you're in C# you prepend them with and i, but in TS you don't iirc.
Yes

**Comment by mgred** [comment]
Changed the description to also have a point regarding the tests

**Comment by mgred** [comment]
@drewjbartlett i just had a look at [githubs project boards](https://help.github.com/articles/about-project-boards/)
Just a quick thought... do you think it would make sense to organise all the refactoring work there to have a better overview of the tasks and duties?

**Comment by drewjbartlett** [comment]
@mgred I am definitely not opposed to this. Let me evaluate shortly what I want to change and I will list it out and we can plan the attack :D

**Comment by mgred** [comment]
Nice thanks, @drewjbarlett
