### ISSUE TITLE
Starting with a Capital on instances which aren't function constructors is against convention

### ISSUE THREAD

**Issue by ricklancee** [rapidjs/rapid.js#9]
I might be nitpicking here but since the classes return instances (objects) and not function constructors they should (per convention) not start with a Capital in the readme.  

```js
var Post = new Rapid({ modelName: 'Post' });

Post.find(1).then((response) => {
    // GET => /api/post/1
});
```

Should be:
```js
var post = new Rapid({ modelName: 'Post' });

post.find(1).then((response) => {
    // GET => /api/post/1
});
```

> By convention, functions that are intended to be used with new should be given names with initial capital letters, and names with initial capital letters should be used only with constructor functions that take the new prefix. This convention gives us a visual cue that can help spot expensive mistakes that the language itself is keen to overlook.
http://archive.oreilly.com/pub/a/javascript/excerpts/javascript-good-parts/bad-parts.html

**Comment by drewjbartlett** [comment]
Yeah, I thought about as well. I'm not opposed to it. So do you suggest that when newing up rapid:

```var photo = new Rapid({})```

Rapid should always be uppercase but `photo` shouldn't? Just want to be clear. I can go through all the docs (which I'd like to release as a repo soon too) and update.

**Comment by ricklancee** [comment]
The convention is that: when you need to use `new` before a function/class then it should start with an Uppercase. So yes `var photo = new Rapid({})`, where photo starts with a lowercase and `Rapid` with an Uppercase. It's a pretty common convention that most people follow.

**Comment by drewjbartlett** [comment]
Okay, I'm on board with it. I can update the docs later tonight to reflect this. Thanks for all the contributions on this!
